const XLSX = require("xlsx");
const fs = require("fs");
const path = require("path");

const excelPath = path.join(
  __dirname,
  "..",
  "MediSync_Medicine_Database.xlsx"
);

const outputPath = path.join(
  __dirname,
  "..",
  "src",
  "data",
  "medicineDatabase.js"
);

if (!fs.existsSync(excelPath)) {
  console.error("❌ Excel file nahi mili:");
  console.error(excelPath);
  process.exit(1);
}

const workbook = XLSX.readFile(excelPath);

if (!workbook.SheetNames.includes("medicines")) {
  console.error('❌ "medicines" sheet nahi mili.');
  process.exit(1);
}

const worksheet = workbook.Sheets["medicines"];

const medicines = XLSX.utils.sheet_to_json(worksheet, {
  defval: "",
  raw: false,
});

const cleanedMedicines = medicines.map((medicine) => {
  const cleaned = {};

  Object.entries(medicine).forEach(([key, value]) => {
    cleaned[key] = String(value ?? "").trim();
  });

  return cleaned;
});

const output = `// ============================================================
// MediSync Medicine Database
// AUTO-GENERATED FILE
// Source: MediSync_Medicine_Database.xlsx
//
// DO NOT EDIT THIS FILE MANUALLY.
// Update the Excel database and run the converter again.
// ============================================================

const medicineDatabase = ${JSON.stringify(
  cleanedMedicines,
  null,
  2
)};

export default medicineDatabase;
`;

fs.mkdirSync(path.dirname(outputPath), {
  recursive: true,
});

fs.writeFileSync(outputPath, output, "utf8");

console.log("");
console.log("✅ Medicine database generated successfully!");
console.log(`📦 Records: ${cleanedMedicines.length}`);
console.log(`📄 Output: ${outputPath}`);
console.log("");